name: build

on:
  pull_request:

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.5'
        bundler-cache: true

    - name: Build site
      env:
        JEKYLL_ENV: production
      run: |
        make _site
